[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/*.obj"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "public, max-age=31536000"
